"""add safes table

Revision ID: 6c7c5ac979f8
Revises: 62248dde9397
Create Date: 2026-01-05 09:36:34.679704

"""
from alembic import op
import sqlalchemy as sa


revision = '6c7c5ac979f8'
down_revision = '62248dde9397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('safe_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safes_id'), 'safes', ['id'], unique=False)
    op.create_index(op.f('ix_safes_safe_date'), 'safes', ['safe_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safes_safe_date'), table_name='safes')
    op.drop_index(op.f('ix_safes_id'), table_name='safes')
    op.drop_table('safes')
    # ### end Alembic commands ###
