"""add debts table

Revision ID: 9b2d2b5c6ac7
Revises: dfdd3cd1c4ad
Create Date: 2026-01-05 15:56:01.842337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '9b2d2b5c6ac7'
down_revision = 'dfdd3cd1c4ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing enum type
    accounttype_enum = postgresql.ENUM('CASH', 'BANK', name='accounttype', create_type=False)

    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('debtor_name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_method', accounttype_enum, nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_debt_date'), 'debts', ['debt_date'], unique=False)
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_debt_date'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###
