"""add payment_method to receipts

Revision ID: dfdd3cd1c4ad
Revises: 6c7c5ac979f8
Create Date: 2026-01-05 09:43:47.991345

"""
from alembic import op
import sqlalchemy as sa


revision = 'dfdd3cd1c4ad'
down_revision = '6c7c5ac979f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('receipts', sa.Column('payment_method', sa.Enum('CASH', 'BANK', name='accounttype'), nullable=True))

    # Set default value for existing records
    op.execute("UPDATE receipts SET payment_method = 'CASH' WHERE payment_method IS NULL")

    # Now make it NOT NULL
    op.alter_column('receipts', 'payment_method', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'payment_method')
    # ### end Alembic commands ###
